language:
  - cpp

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - qt5-default
      - qt5-qmake

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update            ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5       ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew link qt5 --force  ; fi

script:
  - qmake
  - make -s
